---
title: "Def&FormulaPart2"
output: html_document
---

<p>
<u>Permissible Overshoot</u>: The margin of error for the tolerance interval, i.e. how much more the tolerance interval may contain with previously specified probability.
</p>
<p>
<u>Risk</u>: also known as \(\alpha^*\), this is the probability that the true proportion encompassed by the tolerance interval is greater than the desired proportion P plus the permissible overshoot &epsilon;.
</p>
<p>
<u>Order Statistic</u>: In a random sample of size N, the order k statistic is the kth smallest value. Order statistics are frequently used in nonparametric statistical analysis, and some common examples of order statistics include the minimum (i.e. the order 1 statistic), the maximum (i.e. the order N statistic), or the median (i.e. the order (n+1)/2 statistic provided N=2n+1). 
</p>


## Formulas

### Formulas for Nonparametric Calculator

<p>
Using a binary search algorithm, the nonparametric calculator finds the minimal \(n\) and \(k\) such that 
\[P[X \geq k] \geq 1-\alpha\]
and 
\[P[X^* \leq k] \leq \alpha^*\]
are satisfied, where \(X\sim\text{Binom}(n,k,P)\) and \(X^*\sim\text{Binom}(n,k,P+&epsilon;)\). The minimum sample size is then taken to be n. For 1-sided tolerance intervals, the upper limit is given by the order \(k\) statistic and the lower limit is given by the order \(n-k+1\) statistic. For 2-sided tolerance intervals, the upper limit is given by the order \(\lfloor{\frac{n+k}{2}}\rfloor\) statistic and the lower limit is given by the order \(\lceil{\frac{n-k+2}{2}}\rceil\) statistic.
</p>

### Formulas for Normal Calculator

#### 1-Sided

<p>
Using a binary search algorithm, the normal calculator finds the minimal \(n\) such that 
\[t_{n-1,1-\alpha}^{-1}(Z_P\cdot \sqrt{n}) \leq t_{n-1,\alpha^*}^{-1}(Z_{P+&epsilon;}\cdot \sqrt{n}),\]
where \(t_{m,x}(\delta)^{-1}\) denotes the \(x^{th}\) percentile of a noncentral \(t\)-distribution with \(m\) degrees of freedom and non-centrality parameter \(\delta\), and \(Z_x\) denotes the \(x^{th}\) percentile of the standard normal distribution. The sample size is then taken to be this \(n\), and then the upper and lower limits are computed using this value for \(n\) in addition to a user-given sample mean \(\bar{x}\) and sample standard deviation \(s\). The upper and lower limits are computed as 
\[\bar{x} \pm k_1\cdot s\]
where 
\[k_1 = \frac{Z_P+\sqrt{Z^2_P-ab}}{a}\]
with 
\[a = 1 - \frac{Z^2_{\alpha}}{2(n-1)}\]
and 
\[b = Z^2_P - \frac{Z^2_{\alpha}}{n}.\]
</p>

#### 2-Sided

<p>
Using a binary search algorithm, the normal calculator finds the minimal \(n\) such that
\[\frac{(\chi^2_{n-1,1-\alpha})^{-1}}{(\chi^2_{n-1,\alpha^*})^{-1}} \leq \left(\frac{Z_{(1+P+&epsilon;)/2}}{Z_{(1+P)/2}}\right)^2,\]
where \((\chi^2_{m,x})^{-1}\) denotes the \(x^{th}\) percentile of a chi-square distribution with \(m\) degrees of freedom. The sample size is then taken to be this \(n\), and then the upper and lower limits are computed using this value for \(n\) in addition to a user-given sample mean \(\bar{x}\) and sample standard deviation \(s\). The upper and lower limits are computed as
\[\bar{x} \mp k_2\cdot s\]
where
\[k_2 = Z^2_{(1-P)/2}\sqrt{\frac{(n-1)\cdot(1+1/n)}{(\chi^2_{n-1,1-\alpha})^{-1}}}.\]
</p>

## References

<p>
Willam Q Meeker, Gerald J Hahn, Luis A Escobar, “Statistical Intervals: A Guide for Practitioners
and Researchers” (Second Ed.). Wiley Series in Probability and Statistics, 2017.
<br><br>
Minitab, “Methods and Formulas for Sample Size for Tolerance Intervals”, Minitab LLC, 2019. 
<br><br>
PASS Sample Size Software, "Tolerance Intervals for Normal Data", NCSS LLC, 2024.
</p>
















