---
title: "Introduction"
output: html_document
---

## App Features

<p>
This application consists of a nonparametric tolerance interval limit calculator and a normal tolerance interval limit calculator. The nonparametric calculator is to be used when the population distribution is unknown or not normally distributed, thus making it more broadly applicable. The normal calculator is only to be used when the population data is normally (or near normally) distributed, its tolerance interval limits tend to be more precise and resource-efficient than the nonparametric calculator.
<br><br>
Both calculators take in as inputs
<ol>
  <li>Confidence (1-\(\alpha\)),</li>
  <li>Proportion (P),</li>
  <li>Permissible Overshoot aka Margin of Error (&epsilon;), and</li>
  <li>Risk aka \(\alpha^*\).</li>
</ol>
They then both compute the minimum sample size required to compute a tolerance interval based on the above specifications (note that the sample size will differ depending on the calculator used, with the normal calculator typically requiring a smaller sample size). 
<br><br>
The nonparametric calculator then computes an order statistic which provides the limit(s) for a tolerance interval based on the above specifications. The normal calculator, however, takes two additional inputs: sample mean (\(\bar{x}\)) and sample standard deviation (\(s\)), and then it computes the limit(s) for a tolerance interval based on these and the inputs above. A graphical representation of the tolerance interval is also provided for the normal calculator. 
</p>

<!-- No need to modify this disclaimer. It should be uniform across all applications -->
## Disclaimer

<p>While every effort to ensure the accuracy of this app, we DO NOT guarantee that this app is free from defects. This app is provided ‘as is’, and you use the app at your own risk. We make no warranties as to performance, merchantability, fitness for a particular purpose, or any other warranties whether expressed or implied. Under no circumstances shall we be liable for direct, indirect, special, incidental, or consequential damages resulting from the use, misuse, or inability to use this app..</p>

## Questions

<!-- Make sure you replace the (BP Link) with the actual like from the AFIT website -->
For any questions related to the statistics that the functionalities of this application are based upon, please refer to our best practice on tolerance intervals: [Tolerance Interval Demystified](https://www.afit.edu/STAT/statcoe_files/Tolerance%20Intervals%20Demystified.pdf) and [Nonparametric Tolerance Intervals](https://www.afit.edu/STAT/statcoe_files/Nonparametric%20Tolerance%20Intervals%20Best%20Practice.pdf). If you still have questions or wish to contact the STAT COE for formal support, please fill out our ASK-A-STAT form [here](https://www.afit.edu/STAT/page.cfm?page=498).